services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
    expose:
      - 5432
    ports:
      - 5432:5432
  localstack:
    container_name: localstack_demo
    image: localstack/localstack:latest
    ports:
      - "4566:4566"            # LocalStack Gateway
#      - "4510-4559:4510-4559"
    environment:
      #      - DATA_DIR=/tmp/localstack/data # remove deprecated environment variable (more info https://docs.localstack.cloud/references/configuration/#legacy)
      - SERVICES=sqs, dynamodb
      - DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      #      - './localstack:/tmp/localstack' #set correct pathing on docker container  - './localstack:/var/lib/localstack' (more info https://docs.localstack.cloud/references/filesystem/#localstack-volume)
      - './src/main/resources/init-dynamodb.sh:/etc/localstack/init/ready.d/init-dynamodb.sh'
      - './localstack:/var/lib/localstack'
      - "/var/run/docker.sock:/var/run/docker.sock"

