services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
    expose:
      - 5432
    ports:
      - 5432:5432
  localstack:
    container_name: localstack_demo
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs, dynamodb, dynamodbstreams, lambda, logs, sns
      - DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - './src/main/resources/init-dynamodb.sh:/etc/localstack/init/ready.d/init-aws-local.sh'
      - './localstack:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './lambda/build/libs/lambda-0.0.1-SNAPSHOT-all.jar:/tmp/lambda-0.0.1-SNAPSHOT-all.jar'
    networks:
      ls:
        ipv4_address: 10.0.2.20
  application:
    image: ghcr.io/localstack/localstack-docker-debug:main
    entrypoint: ""
    command: [ "sleep", "infinity" ]
    dns:
      - 10.0.2.20
    networks:
      - ls
networks:
  ls:
    ipam:
      config:
        - subnet: 10.0.2.0/24


