insert into USERS (USER_ID, NAME, SEQUENCE_NUMBER) values ('cfd07af7-34aa-4b51-8259-b2781511f03d', 'Isabella Bennett', 1);
insert into USERS (USER_ID, NAME, SEQUENCE_NUMBER) values ('a451ccb2-ca2d-4052-9a33-22a53f055f39', 'Lucas Patel', 1);
insert into USERS (USER_ID, NAME, SEQUENCE_NUMBER) values ('6aec5126-4fe1-4f74-97c1-c90aee59a54d', 'Sophia Nguyen', 1);
insert into USERS (USER_ID, NAME, SEQUENCE_NUMBER) values ('5316e0e7-0bea-4731-b476-c008c6720584', 'Ethan Garcia', 1);
insert into USERS (USER_ID, NAME, SEQUENCE_NUMBER) values ('8378955d-47e6-4c64-8713-c28bfd6cb73b', 'Mia Thompson', 1);
insert into USERS (USER_ID, NAME, SEQUENCE_NUMBER) values ('a11597c8-08e2-4bb0-a374-e4da8139fef1', 'Oliver Khan', 1);
insert into USERS (USER_ID, NAME, SEQUENCE_NUMBER) values ('b932e786-5983-4062-a948-231d3ece4d17', 'Emma Rodriguez', 1);
insert into USERS (USER_ID, NAME, SEQUENCE_NUMBER) values ('5e29ac9d-d64b-457e-bb45-8b037dad6ae4', 'Liam Sullivan', 1);
insert into USERS (USER_ID, NAME, SEQUENCE_NUMBER) values ('b62bc4db-e39f-408b-a435-7266db8115e4', 'Ava Martinez', 1);
insert into USERS (USER_ID, NAME, SEQUENCE_NUMBER) values ('8949ece0-ca7c-4eba-81c6-734ff2c341fe', 'Noah Clark', 1);
insert into USERS (USER_ID, NAME, SEQUENCE_NUMBER) values ('95561c5d-6f59-4280-9095-2b15106cae37', 'Amelia Wright', 1);
insert into USERS (USER_ID, NAME, SEQUENCE_NUMBER) values ('4e723f06-9b2b-43ad-b18e-f3a56f42a2fc', 'Elijah Cooper', 1);
insert into USERS (USER_ID, NAME, SEQUENCE_NUMBER) values ('19fed54e-c3e4-425c-9d02-c3608f4e99bb', 'Charlotte Walker', 1);
insert into USERS (USER_ID, NAME, SEQUENCE_NUMBER) values ('f8fdd54c-57cc-40aa-b397-48d331216480', 'Harper Carter', 1);
insert into USERS (USER_ID, NAME, SEQUENCE_NUMBER) values ('75366564-041c-45b9-bade-1fe4801e484b', 'William Baker', 1);
insert into USERS (USER_ID, NAME, SEQUENCE_NUMBER) values ('a4b1f793-733a-4116-940b-12f735fb16c8', 'Abigail Roberts', 1);
insert into USERS (USER_ID, NAME, SEQUENCE_NUMBER) values ('649ebc7f-7bbb-4747-900b-068df0ed0d3a', 'James Morgan', 1);
insert into USERS (USER_ID, NAME, SEQUENCE_NUMBER) values ('bc0001fb-516d-4b4b-a80d-942a8ffd6e83', 'Evelyn Hayes', 1);
insert into USERS (USER_ID, NAME, SEQUENCE_NUMBER) values ('ead68969-25e6-4217-bca1-9a5f470f5ff8', 'Alexander Foster', 1);
insert into USERS (USER_ID, NAME, SEQUENCE_NUMBER) values ('dc613345-9c57-4a74-9639-cc710e94c288', 'Christine J. Wilson', 1);
insert into USERS (USER_ID, NAME, SEQUENCE_NUMBER) values ('9639db57-9a64-436a-ac9e-a4a9a45a053c', 'Benjamin Lewis', 1);

-- Names generated by and courtesy of ChatGPT --